name: trail_sync
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    icons_plus: ^5.0.0
    go_router: ^16.1.0
    firebase_auth: ^6.0.0
    cloud_firestore: ^6.0.0
    firebase_core: ^4.0.0
    flutter_riverpod: ^2.6.1
    flutter_background_geolocation: '^4.12.0'
    latlong2: ^0.9.1
    flutter_compass: ^0.8.1
    maplibre_gl: ^0.22.0
    geolocator: ^14.0.2
    fl_chart: ^1.0.0
    geocoding: ^4.0.0
    app_settings: ^6.1.1
    intl: ^0.20.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

assets:
    - assets/images/google.png
