// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxa3N4PyaI6jCAfCc83ZH1V-LJzdN3Js',
    appId: '1:950483726466:web:055ec8237c43510a1cc49b',
    messagingSenderId: '950483726466',
    projectId: 'flutter-chat-app-100d6',
    authDomain: 'flutter-chat-app-100d6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-100d6.firebasestorage.app',
    measurementId: 'G-8CLMF50DB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRLuttsX0DeAwck11WvUlh6DkKYL9pXx4',
    appId: '1:950483726466:android:c6bbce63d7ee47031cc49b',
    messagingSenderId: '950483726466',
    projectId: 'flutter-chat-app-100d6',
    storageBucket: 'flutter-chat-app-100d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2o9QPQLA9Dy8ZjFKRg2fsQhmUwKQannI',
    appId: '1:950483726466:ios:9a7d1907b92edc1f1cc49b',
    messagingSenderId: '950483726466',
    projectId: 'flutter-chat-app-100d6',
    storageBucket: 'flutter-chat-app-100d6.firebasestorage.app',
    iosBundleId: 'com.example.trailSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2o9QPQLA9Dy8ZjFKRg2fsQhmUwKQannI',
    appId: '1:950483726466:ios:9a7d1907b92edc1f1cc49b',
    messagingSenderId: '950483726466',
    projectId: 'flutter-chat-app-100d6',
    storageBucket: 'flutter-chat-app-100d6.firebasestorage.app',
    iosBundleId: 'com.example.trailSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzxa3N4PyaI6jCAfCc83ZH1V-LJzdN3Js',
    appId: '1:950483726466:web:3e7a4122ea598abd1cc49b',
    messagingSenderId: '950483726466',
    projectId: 'flutter-chat-app-100d6',
    authDomain: 'flutter-chat-app-100d6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-100d6.firebasestorage.app',
    measurementId: 'G-EEF77RSXPP',
  );

}